### ISSUE TITLE
Funksteckdosen Quigg Aldi 2016 GT-9000

### ISSUE THREAD

**Issue by TiEr92** [RFD-FHEM/RFFHEM#93]
Hi, 
gibt es ne möglich die Funksteckdosen einzubinden? Die haben leider nen rolling-code, wurden aber von schon decodiert: 
[https://github.com/pilight/pilight/blob/development/libs/pilight/protocols/433.92/quigg_gt9000.c](url)
[https://forum.pilight.org/showthread.php?tid=1496&highlight=quigg](url)

Log von Signalduino:

Reihe 3:
An:
```
2016.08.08 18:44:37 4: sduino/msg READ: MU;P0=-591;P1=408;P2=-1124;P3=916;P5=-13052;P6=32001;P7=-7240;D=73030123012121230121230303030303012301212303012156;CP=1;
2016.08.08 18:44:37 5: sduino: applying filterfunc SIGNALduino_filterSign
2016.08.08 18:44:37 4: sduino: Fingerprint for MU Protocol id 21 -> einhell garagedoor matches, trying to demodulate
2016.08.08 18:44:37 5: sduino: Starting demodulation at Position 2
2016.08.08 18:44:37 4: sduino: Fingerprint for MU Protocol id 26 -> remote26 matches, trying to demodulate
2016.08.08 18:44:37 5: sduino: Starting demodulation at Position 2
2016.08.08 18:44:37 4: sduino: Fingerprint for MU Protocol id 27 -> remote27 matches, trying to demodulate
2016.08.08 18:44:37 5: sduino: Starting demodulation at Position 2
2016.08.08 18:44:37 4: sduino: Fingerprint for MU Protocol id 28 -> IC Ledspot matches, trying to demodulate
2016.08.08 18:44:37 5: sduino: Starting demodulation at Position 2
2016.08.08 18:44:37 4: sduino: Fingerprint for MU Protocol id 30 -> unitec47031 matches, trying to demodulate
2016.08.08 18:44:37 5: sduino: Starting demodulation at Position 2
2016.08.08 18:44:37 4: sduino: Fingerprint for MU Protocol id 31 -> pollin isotronic matches, trying to demodulate
2016.08.08 18:44:37 5: sduino: Starting demodulation at Position 10
2016.08.08 18:44:37 4: sduino: Fingerprint for MU Protocol id 36 -> socket36 matches, trying to demodulate
2016.08.08 18:44:37 5: sduino: Starting demodulation at Position 2
2016.08.08 18:44:37 5: sduino: applying filterfunc SIGNALduino_compPattern
2016.08.08 18:44:37 4: sduino: Fingerprint for MU Protocol id 8 -> TX3 Protocol matches, trying to demodulate
2016.08.08 18:44:37 5: sduino: Starting demodulation at Position 1
```

Aus:
```
2016.08.08 18:45:21 4: sduino/msg READ: MU;P0=372;P1=-1172;P2=888;P4=-628;P6=-7182;D=6242401242401242401010124240101240101012424240101;CP=0;
2016.08.08 18:45:21 5: sduino: applying filterfunc SIGNALduino_filterSign
2016.08.08 18:45:21 4: sduino: Fingerprint for MU Protocol id 21 -> einhell garagedoor matches, trying to demodulate
2016.08.08 18:45:21 5: sduino: Starting demodulation at Position 2
2016.08.08 18:45:21 4: sduino: Fingerprint for MU Protocol id 26 -> remote26 matches, trying to demodulate
2016.08.08 18:45:21 5: sduino: Starting demodulation at Position 2
2016.08.08 18:45:21 4: sduino: Fingerprint for MU Protocol id 27 -> remote27 matches, trying to demodulate
2016.08.08 18:45:21 5: sduino: Starting demodulation at Position 2
2016.08.08 18:45:21 4: sduino: Fingerprint for MU Protocol id 28 -> IC Ledspot matches, trying to demodulate
2016.08.08 18:45:21 5: sduino: Starting demodulation at Position 2
2016.08.08 18:45:21 4: sduino: Fingerprint for MU Protocol id 31 -> pollin isotronic matches, trying to demodulate
2016.08.08 18:45:21 5: sduino: Starting demodulation at Position 18
2016.08.08 18:45:21 4: sduino: Fingerprint for MU Protocol id 36 -> socket36 matches, trying to demodulate
2016.08.08 18:45:21 5: sduino: Starting demodulation at Position 2
2016.08.08 18:45:21 5: sduino: applying filterfunc SIGNALduino_compPattern
2016.08.08 18:45:21 4: sduino: Fingerprint for MU Protocol id 8 -> TX3 Protocol matches, trying to demodulate
2016.08.08 18:45:21 5: sduino: Starting demodulation at Position 1
```

Reihe4:
An:
```
2016.08.08 18:46:51 4: sduino/msg READ: MU;P0=-644;P1=926;P2=379;P3=-1143;P6=2918;P7=-7266;D=67001023101010101023231023231023101023102323231023671;CP=2;
2016.08.08 18:46:51 5: sduino: applying filterfunc SIGNALduino_filterSign
2016.08.08 18:46:51 4: sduino: Fingerprint for MU Protocol id 21 -> einhell garagedoor matches, trying to demodulate
2016.08.08 18:46:51 5: sduino: Starting demodulation at Position 2
2016.08.08 18:46:51 4: sduino: Fingerprint for MU Protocol id 26 -> remote26 matches, trying to demodulate
2016.08.08 18:46:51 5: sduino: Starting demodulation at Position 2
2016.08.08 18:46:51 4: sduino: Fingerprint for MU Protocol id 27 -> remote27 matches, trying to demodulate
2016.08.08 18:46:51 5: sduino: Starting demodulation at Position 2
2016.08.08 18:46:51 4: sduino: Fingerprint for MU Protocol id 28 -> IC Ledspot matches, trying to demodulate
2016.08.08 18:46:51 5: sduino: Starting demodulation at Position 2
2016.08.08 18:46:51 4: sduino: Fingerprint for MU Protocol id 31 -> pollin isotronic matches, trying to demodulate
2016.08.08 18:46:51 5: sduino: Starting demodulation at Position 19
2016.08.08 18:46:51 4: sduino: Fingerprint for MU Protocol id 36 -> socket36 matches, trying to demodulate
2016.08.08 18:46:51 5: sduino: Starting demodulation at Position 2
2016.08.08 18:46:51 5: sduino: applying filterfunc SIGNALduino_compPattern
2016.08.08 18:46:51 4: sduino: Fingerprint for MU Protocol id 8 -> TX3 Protocol matches, trying to demodulate
2016.08.08 18:46:51 5: sduino: Starting demodulation at Position 4
```

Aus:
```
2016.08.08 18:47:09 4: sduino/msg READ: MS;P0=-484;P1=292;P3=-1266;P6=-2369;P7=1059;D=16707013707013131313701313131370701313707013137013;CP=1;SP=6;
2016.08.08 18:47:09 4: sduino/msg READ: MU;P0=32001;P1=399;P2=-990;P3=942;P4=-617;P5=608;P7=-9008;D=34121212123452121212343412123434121234170;CP=1;
2016.08.08 18:47:09 5: sduino: applying filterfunc SIGNALduino_filterSign
2016.08.08 18:47:09 4: sduino: Fingerprint for MU Protocol id 21 -> einhell garagedoor matches, trying to demodulate
2016.08.08 18:47:09 5: sduino: Starting demodulation at Position 2
2016.08.08 18:47:09 4: sduino: Fingerprint for MU Protocol id 26 -> remote26 matches, trying to demodulate
2016.08.08 18:47:09 5: sduino: Starting demodulation at Position 2
2016.08.08 18:47:09 4: sduino: Fingerprint for MU Protocol id 27 -> remote27 matches, trying to demodulate
2016.08.08 18:47:09 5: sduino: Starting demodulation at Position 2
2016.08.08 18:47:09 4: sduino: Fingerprint for MU Protocol id 28 -> IC Ledspot matches, trying to demodulate
2016.08.08 18:47:09 5: sduino: Starting demodulation at Position 2
2016.08.08 18:47:09 4: sduino: Fingerprint for MU Protocol id 31 -> pollin isotronic matches, trying to demodulate
2016.08.08 18:47:09 5: sduino: Starting demodulation at Position 13
2016.08.08 18:47:09 4: sduino: Fingerprint for MU Protocol id 36 -> socket36 matches, trying to demodulate
2016.08.08 18:47:09 5: sduino: Starting demodulation at Position 2
2016.08.08 18:47:09 5: sduino: applying filterfunc SIGNALduino_compPattern
2016.08.08 18:47:09 4: sduino: Fingerprint for MU Protocol id 40 -> romotec matches, trying to demodulate
2016.08.08 18:47:09 5: sduino: Starting demodulation at Position 2
2016.08.08 18:47:09 5: sduino: dispatching bits: 0 0 1 1 0 0 1 1 0 0 1 0
2016.08.08 18:47:09 4: sduino: decoded matched MU Protocol id 40 dmsg u40#332 length 12
2016.08.08 18:47:09 5: sduino: converted Data to (u40#332)
2016.08.08 18:47:09 5: sduino dispatch u40#332
2016.08.08 18:47:09 4: SIGNALduino_unknown incomming msg: u40#332
2016.08.08 18:47:09 4: SIGNALduino_unknown rawData: 332
2016.08.08 18:47:09 4: SIGNALduino_unknown Protocol: 40
2016.08.08 18:47:09 4: SIGNALduino_unknown converted to bits: 001100110010
2016.08.08 18:47:09 4: sduino: Fingerprint for MU Protocol id 8 -> TX3 Protocol matches, trying to demodulate
2016.08.08 18:47:09 5: sduino: Starting demodulation at Position 0
2016.08.08 18:47:09 4: sduino: Fingerprint for MU Protocol id 9 -> CTW 600 matches, trying to demodulate
2016.08.08 18:47:09 5: sduino: Starting demodulation at Position 0

```

**Comment by sidey79** [comment]
Ich habe es mir mal angesehen.

Demodulieren ist wohl einfach. Dann fehlt aber ein Modul, dass diese Funkbefehle versteht.
Kannst Du das Modul programmieren?

**Comment by TiEr92** [comment]
Hi Sidey,
danke das du dir das mal angeguckt hast. 

Ich kann es mal probieren, aber ich bräuchte ein wenig Unterstützung, wie ich da vorgehen muss. Ich habe leider noch keine Ahnung von der Decodierung von Funksignalen.

**Comment by sidey79** [comment]
Das demodulieren baue ich ein.
Danach braucht es ein eigenes Modul.

Was die Bits bedeuten, steht in deinem Link.

**Comment by sidey79** [comment]
Protokoll Definition;
clock=ca. 400
start/sync = -7200, +900,-600  [-15,2,-1]
one = 900,-600 [2,-1]
zero = 390,1200 [1,3]

**Comment by sidey79** [comment]
Bitte mal testen

**Comment by ohuf** [comment]
Hallo Sidey

Ich bin eben über diesen Thread gestolpert, da ich nun auch einen Sack voll dieser Funksteckdosen ergattert habe. Die Bezeichnung auf der FB ist GT-3000, die Steckdosen tragen die Modellnummer GT-FSA-04.
SD ordnet meine FB im FHEM-Log der GT-9000 zu... DIe Signatur scheint also übereinzustimmen...

Da ja bislang noch niemand ein Modul hierfür geschrieben hat, würde ich es mal versuchen.
Leider fehlt mir dazu eine Doku.
Kannst du mir einen Link schicken?

Da ich komplett neu bei FHEM bin, weiss ich noch nicht einmal, wo die Client Module Files stehen, bzw. wie die heissen müssten...

Danke & Gruß,
ohuf.

**Comment by pejonp** [comment]
Hi ohuf,

Schau dir doch einmal das IT - InterTechn-modul an dort werden auch Steckdosen geschaltet.

**Comment by ohuf** [comment]
Hallo

Mein Problem ist schonmal, das ClientModule für InterTechno zu finden: Ist es (irgendwo inline) in der SIGNALduino.pm enthalten, oder ist es die Datei /opt/fhem/FHEM/10_IT.pm ??

**Comment by pejonp** [comment]
Ja 10_IT.pm

**Comment by ohuf** [comment]
Hat sich erledigt: Die Steckdosen konnte ich nicht decodieren.

Danke & Gruß

**Comment by HomeAutoUser** [comment]
Hallo, dann können wir dir gern helfen 😊 So haben wir alle was davon

**Comment by Ralf9** [comment]
add support for GT-9000 protocol 
https://github.com/pilight/pilight/pull/215/commits/992aae16c9684646a8bc96b128b812ee93b27fa7

**Comment by sidey79** [comment]
Hier hat sich schon lange nichts mehr getan. Ich schließe das Issue. Bitte wieder öffnen, wenn es noch benötigt wird.

**Comment by hackfred64** [comment]
Sidey, können wir den Pfad bitte wieder aufmachen?! Ich habe diese GT-3000 / GT-FSA-04 Kombination. Auf einem Arduino (rcswitch+C1101) habe ich das Protokoll schon laufen. Ich kämpfe nur bisher vergeblich das mit fhem/signalduino hinzubekommen. Mir geht es hauptsächlich darum die Mechanismen besser zu verstehen, auf Dauer "darf" ich die Steckdosen ohnehin nicht automatisieren. Da bekomme ich "Veto" von der Familie ;-)

**Comment by sidey79** [comment]
@hackfred64 

Kein Problem. Habe es wieder geöffnet.
Kannst Du denn ein paar RAW Nachrichten (ab Verbose 4) dem Sender zuordnen?

**Comment by hackfred64** [comment]
On:
`2019.12.22 09:57:16 4: somfyoben/msg READredu: MU;P0=414;P1=261;P2=-1124;P3=929;P4=-619;P5=-2417;P6=2974;P7=-7334;D=1234341212153434343434123412123434121234341212343412343412121534343434341234121234341212343412123434123434121215343434343412341212343412123434121234341234341212673434343434023402023434020234340202343402343402026734343434340234020234340202343402023434023;CP=3;R=21;O;
2019.12.22 09:57:16 4: somfyoben: Fingerprint for MU Protocol id 8 -> TX3 Protocol matches, trying to demodulate
2019.12.22 09:57:16 4: somfyoben: Fingerprint for MU Protocol id 26 -> remote matches, trying to demodulate
2019.12.22 09:57:16 4: somfyoben: Fingerprint for MU Protocol id 27 -> remote matches, trying to demodulate
2019.12.22 09:57:16 4: somfyoben: Decoded matched MU Protocol id 27 dmsg u27#059993 length 24 dispatch(1/4) RSSI = -63.5
2019.12.22 09:57:16 4: SIGNALduino_unknown incomming msg: u27#059993
2019.12.22 09:57:16 4: SIGNALduino_unknown rawData: 059993
2019.12.22 09:57:16 4: SIGNALduino_unknown Protocol: 27
2019.12.22 09:57:16 4: SIGNALduino_unknown converted to bits: 000001011001100110010011
2019.12.22 09:57:16 4: SIGNALduino_unknown somfyoben Protocol:27 | To help decode or debug, please add u27! (attr somfyoben development u27)
2019.12.22 09:57:16 4: Unknown, please report
2019.12.22 09:57:16 3: somfyoben: Unknown code u27#059993, help me!
2019.12.22 09:57:16 4: somfyoben: Fingerprint for MU Protocol id 34 -> QUIGG | LIBRA matches, trying to demodulate
2019.12.22 09:57:16 4: somfyoben: Fingerprint for MU Protocol id 49 -> QUIGG_GT-9000 matches, trying to demodulate
2019.12.22 09:57:16 4: somfyoben: Decoded matched MU Protocol id 49 dmsg U49#FA666C length 24 dispatch(1/4) RSSI = -63.5
2019.12.22 09:57:16 4: somfyoben/msg READredu: MU;P0=924;P1=-612;P2=425;P3=-1120;P4=2990;P5=-7326;D=0123234501010101012301232301012323010123230101230101232345010101010123012323010123230101232301012301012320;CP=2;R=17;
2019.12.22 09:57:16 4: somfyoben: Fingerprint for MU Protocol id 8 -> TX3 Protocol matches, trying to demodulate
2019.12.22 09:57:16 4: somfyoben: Fingerprint for MU Protocol id 19 -> minify matches, trying to demodulate
2019.12.22 09:57:16 4: somfyoben: Decoded matched MU Protocol id 19 dmsg u19#FA666C length 24 dispatch(1/4) RSSI = -65.5
2019.12.22 09:57:16 4: SIGNALduino_unknown incomming msg: u19#FA666C
2019.12.22 09:57:16 4: SIGNALduino_unknown rawData: FA666C
2019.12.22 09:57:16 4: SIGNALduino_unknown Protocol: 19
2019.12.22 09:57:16 4: SIGNALduino_unknown converted to bits: 111110100110011001101100
2019.12.22 09:57:16 4: SIGNALduino_unknown somfyoben Protocol:19 | To help decode or debug, please add u19! (attr somfyoben development u19)
2019.12.22 09:57:16 4: Unknown, please report
2019.12.22 09:57:16 3: somfyoben: Unknown code u19#FA666C, help me!
2019.12.22 09:57:16 4: somfyoben: Fingerprint for MU Protocol id 27 -> remote matches, trying to demodulate
2019.12.22 09:57:16 4: somfyoben: Decoded matched MU Protocol id 27 dmsg u27#059993 length 24 dispatch(1/4) RSSI = -65.5
2019.12.22 09:57:16 4: somfyoben: Fingerprint for MU Protocol id 34 -> QUIGG | LIBRA matches, trying to demodulate
2019.12.22 09:57:16 4: somfyoben: Fingerprint for MU Protocol id 49 -> QUIGG_GT-9000 matches, trying to demodulate
2019.12.22 09:57:16 4: somfyoben: Decoded matched MU Protocol id 49 dmsg U49#FA666C length 24 dispatch(1/4) RSSI = -65.5
2019.12.22 09:57:16 4: somfyoben: Decoded matched MU Protocol id 49 dmsg U49#FA666C length 24 dispatch(2/4) RSSI = -65.5
2019.12.22 09:57:16 4: somfyoben Dispatch: U49#FA666C, Dropped due to short time or equal msg
`
Off:

`2019.12.22 09:59:00 4: somfyoben/msg READredu: MU;P0=-1129;P1=260;P2=915;P3=-631;P4=-2430;P5=2968;P6=-7332;P7=416;D=0101010101023231023232323231010142323232323102323101010101010232310232323232310101423232323231023231010101010102323102323232323101014232323232310232310101010101023231023232323231010562323232323702323707070707070232370232323232370705623232323237023237070;CP=2;R=27;O;
2019.12.22 09:59:00 4: somfyoben: Fingerprint for MU Protocol id 8 -> TX3 Protocol matches, trying to demodulate
2019.12.22 09:59:00 4: somfyoben: Fingerprint for MU Protocol id 26 -> remote matches, trying to demodulate
2019.12.22 09:59:00 4: somfyoben: Fingerprint for MU Protocol id 27 -> remote matches, trying to demodulate
2019.12.22 09:59:00 4: somfyoben: Decoded matched MU Protocol id 27 dmsg u27#04FC83 length 24 dispatch(1/4) RSSI = -60.5
2019.12.22 09:59:00 4: SIGNALduino_unknown incomming msg: u27#04FC83
2019.12.22 09:59:00 4: SIGNALduino_unknown rawData: 04FC83
2019.12.22 09:59:00 4: SIGNALduino_unknown Protocol: 27
2019.12.22 09:59:00 4: SIGNALduino_unknown converted to bits: 000001001111110010000011
2019.12.22 09:59:00 4: SIGNALduino_unknown somfyoben Protocol:27 | To help decode or debug, please add u27! (attr somfyoben development u27)
2019.12.22 09:59:00 4: Unknown, please report
2019.12.22 09:59:00 3: somfyoben: Unknown code u27#04FC83, help me!
2019.12.22 09:59:01 4: somfyoben: Fingerprint for MU Protocol id 34 -> QUIGG | LIBRA matches, trying to demodulate
2019.12.22 09:59:01 4: somfyoben: Fingerprint for MU Protocol id 49 -> QUIGG_GT-9000 matches, trying to demodulate
2019.12.22 09:59:01 4: somfyoben: Decoded matched MU Protocol id 49 dmsg U49#FB037C length 24 dispatch(1/4) RSSI = -60.5
2019.12.22 09:59:01 4: somfyoben/HandleWriteQueue: nothing to send, stopping timer
2019.12.22 09:59:01 4: somfyoben/msg READredu: MU;P0=-1133;P1=412;P2=923;P3=-620;P4=2972;P5=-7334;D=01010102323102323232323101045232323232310232310101010101023231023232323231010452323232323102323101010101010232310232323232310;CP=1;R=27;
2019.12.22 09:59:01 4: somfyoben: Fingerprint for MU Protocol id 8 -> TX3 Protocol matches, trying to demodulate
2019.12.22 09:59:01 4: somfyoben: Fingerprint for MU Protocol id 27 -> remote matches, trying to demodulate
2019.12.22 09:59:01 4: somfyoben: Decoded matched MU Protocol id 27 dmsg u27#04FC83 length 24 dispatch(1/4) RSSI = -60.5
2019.12.22 09:59:01 4: somfyoben: Fingerprint for MU Protocol id 34 -> QUIGG | LIBRA matches, trying to demodulate
2019.12.22 09:59:01 4: somfyoben: Fingerprint for MU Protocol id 49 -> QUIGG_GT-9000 matches, trying to demodulate
2019.12.22 09:59:01 4: somfyoben: Decoded matched MU Protocol id 49 dmsg U49#FB037C length 24 dispatch(1/4) RSSI = -60.5
2019.12.22 09:59:01 4: somfyoben: Decoded matched MU Protocol id 49 dmsg U49#FB037C length 24 dispatch(2/4) RSSI = -60.5
2019.12.22 09:59:01 4: somfyoben Dispatch: U49#FB037C, Dropped due to short time or equal msg
`

**Comment by elektron-bbs** [comment]
Das Protokoll sollte seit 16.12.2019 in der Entwicklerversion sein.
@hackfred64 
Bitte mal ein Update auf die aktuelle Entwicklerversion durchführen:
update all https://raw.githubusercontent.com/RFD-FHEM/RFFHEM/dev-r34/controls_signalduino.txt

**Comment by hackfred64** [comment]
Danke! Das sieht jetzt anders aus aber ist das wirklich besser??

`2019.12.22 10:30:29 4: somfyoben: Read, msg READredu: MS;P0=-487;P1=273;P2=-2406;P3=975;P5=-1268;D=12303030303030151530151530151515303015301530301515;CP=1;SP=2;R=6;m2;
2019.12.22 10:30:29 4: somfyoben: Parse_MS, Matched MS Protocol id 55 -> QUIGG_GT-1000
2019.12.22 10:30:29 4: somfyoben: Parse_MS, Decoded matched MS Protocol id 55 dmsg iFC91AC length 24  RSSI = -71
2019.12.22 10:30:30 4: somfyoben IT: message "iFC91AC" (7)
2019.12.22 10:30:30 4: somfyoben IT: msgcode "" (0) bin = 111111001001000110101100
2019.12.22 10:30:30 4: somfyoben IT: 1527xfc91a not defined (Switch code: 1100)
2019.12.22 10:30:30 4: autocreate: received 1 event(s) for 'IT 1527xfc91a 1100 0000' during the last 30 seconds
2019.12.22 10:30:30 4: autocreate: ignoring event for 'IT 1527xfc91a 1100 0000': at least 2 needed
2019.12.22 10:30:30 4: somfyoben: Read, msg READredu: MU;P0=-631;P1=392;P2=-31544;P3=920;P5=-1153;P6=2972;P7=-7328;D=5673030303030301515301515301515153030153015303015156730303030303015153015153015151530301530153030151567303030303030151530151530151515303015301530301515673030303030301515301515301515153030153015303015120;CP=1;R=3;
2019.12.22 10:30:30 4: somfyoben: Parse_MU, Fingerprint for MU Protocol id 8 -> TX3 Protocol matches, trying to demodulate
2019.12.22 10:30:30 4: somfyoben: Parse_MU, Fingerprint for MU Protocol id 34 -> QUIGG | LIBRA | Mandolyn | Pollin ISOTRONIC matches, trying to demodulate
2019.12.22 10:30:30 4: somfyoben: Parse_MU, Fingerprint for MU Protocol id 49.1 -> GT-9000 matches, trying to demodulate
2019.12.22 10:30:30 4: somfyoben: Parse_MU, Decoded matched MU Protocol id 49.1 dmsg P49#FC91AC length 24 dispatch(1/4) RSSI = -72.5
2019.12.22 10:30:30 4: somfyoben: SD_GT_Parse FC91AC, possible codes version 1 F0733 or version 2 F0BC3
2019.12.22 10:30:30 4: somfyoben: SD_GT_Parse FC91AC, found version 0 with systemCode 0
2019.12.22 10:30:30 1: somfyoben: SD_GT_Parse UNDEFINED SD_GT_LEARN device detected
2019.12.22 10:30:30 4: autocreate: received 1 event(s) for 'SD_GT LEARN' during the last 180 seconds
2019.12.22 10:30:30 4: autocreate: ignoring event for 'SD_GT LEARN': at least 5 needed
2019.12.22 10:30:30 4: somfyoben: Parse_MU, Decoded matched MU Protocol id 49.1 dmsg P49#FC91AC length 24 dispatch(2/4) RSSI = -72.5
2019.12.22 10:30:30 4: somfyoben: Dispatch, P49#FC91AC, Dropped due to short time or equal msg
2019.12.22 10:30:30 4: somfyoben: Parse_MU, Decoded matched MU Protocol id 49.1 dmsg P49#FC91AC length 24 dispatch(3/4) RSSI = -72.5
2019.12.22 10:30:30 4: somfyoben: Dispatch, P49#FC91AC, Dropped due to short time or equal msg`

**Comment by hackfred64** [comment]
Asche auf mein Haupt, erst das Logfile genauer ansehen und dann posten!
Also: läuft, Danke für die schnelle Hilfe!

**Comment by hackfred64** [comment]
Eins wundert mich aber schon: im Verlauf des Anlernen sind auch zwei IT Devices per autocreate angelegt worden. Die Befehle kamen explizit von der Fernbedienung !?...

**Comment by elektron-bbs** [comment]
Das Funkprotokoll ist halt ähnlich. Wenn du dieses IT-Protokoll nicht benötigst, kannst du Protokoll 55 ja deaktivieren.

**Comment by hackfred64** [comment]
Alles gut, ich wollte nur sicherstellen, dass hier nicht fälschlicherweise Befehle im falschen Pfad gelandet sind.

Danke nochmal!

**Comment by elektron-bbs** [comment]
Das Protokoll ist seit 16.12.2019 in der Entwicklerversion sein.
